insert into Todo(title,status) values('Learn Spring Boot',false)
insert into Todo(title,status) values('Visit Grocery Store',false)
insert into Todo(title,status) values('Learn AWS',false)
insert into Todo(title,status) values('Swimming',false)
insert into Todo(title,status) values('Yoga',false)